name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: npm
      - run: npm ci
      - run: npm test
      - run: npx semantic-release
        # build happens automatically in the package.json postversion script when
        # semantic release increments the version see https://bit.ly/3yllLkR
        env:
          GITHUB_TOKEN: ${{ secrets.CROIABOT_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GH_TOKEN: ${{ secrets.CROIABOT_PAT }}
          GIT_AUTHOR_NAME: "croiabot"
          GIT_AUTHOR_EMAIL: "croiabot@gmail.com"
          GIT_COMMITTER_NAME: "croiabot"
          GIT_COMMITTER_EMAIL: "croiabot@gmail.com"
