name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: npm
      - run: npm ci
      # - run: npm test
      # - run: npm run build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.PAT }}
          GH_TOKEN: ${{ secrets.PAT }}
          GIT_AUTHOR_NAME: "@CoreyMartin"
          GIT_AUTHOR_EMAIL: "coreyn.martin@gmail.com"
          GIT_COMMITTER_NAME: "@CoreyMartin"
          GIT_COMMITTER_EMAIL: "coreyn.martin@gmail.com"
