name: validate sematic PR title

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize, reopened]

jobs:
  validate_pr_title:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: '^(feat|bug|chore|fix)(\(.*\))*:\s+.*'
          allowed_prefixes: ""
          prefix_case_sensitive: true
          min_length: 10
          max_length: 80
